name: Deploy to Testing or Production Environment

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          echo "WHATSAPP_API_TOKEN=${{ secrets.XEGURIDAD2_API_TOKEN }}" >> $GITHUB_ENV
          echo "WHATSAPP_API_URL=${{ secrets.XEGURIDAD2_WB_API }}" >> $GITHUB_ENV
          echo "NAMESPACE=Xeguridad2" >> $GITHUB_ENV
          echo "repo_path=/home/exasa/XeguridadBot-pruebas/XeguridadBot" >> $GITHUB_ENV
          echo "service=flask.service" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "WHATSAPP_API_TOKEN=${{ secrets.XEGURIDAD_API_TOKEN }}" >> $GITHUB_ENV
          echo "WHATSAPP_API_URL=${{ secrets.XEGURIDAD_WB_API }}" >> $GITHUB_ENV
          echo "NAMESPACE=Xeguridad" >> $GITHUB_ENV
          echo "repo_path=/home/exasa/XeguridadBot-produccion/XeguridadBot" >> $GITHUB_ENV
          echo "service=flask_main.service" >> $GITHUB_ENV 
        fi

    - name: Push changes to GitHub
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/DanielFuentes918/XeguridadBot.git
        git push origin ${{ github.ref_name }}


