name: Deploy to Testing or Production Environment

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create .env file with secrets
      run: |
        echo "WHATSAPP_API_TOKEN=${{ secrets.XEGURIDAD2_API_TOKEN }}" >> .env
        echo "WHATSAPP_API_URL=${{ secrets.XEGURIDAD2_WB_API }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "XEGURIDAD_API_URL=${{ secrets.XEGURIDAD_API_URL }}" >> .env
        echo "XEGURIDAD_PASSWORD=${{ secrets.XEGURIDAD_PASSWORD }}" >> .env
        echo "PASSWORD_MONGO=${{ secrets.PASSWORD_MONGO }}" >> .env
        echo "NAMESPACE=Xeguridad2" >> .env
        echo "repo_path=/home/exasa/XeguridadBot-pruebas/XeguridadBot" >> .env
        echo "service=flask.service" >> .env
      if: github.ref == 'refs/heads/dev'

    - name: Create .env file for production
      run: |
        echo "WHATSAPP_API_TOKEN=${{ secrets.XEGURIDAD_API_TOKEN }}" >> .env
        echo "WHATSAPP_API_URL=${{ secrets.XEGURIDAD_WB_API }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "XEGURIDAD_API_URL=${{ secrets.XEGURIDAD_API_URL }}" >> .env
        echo "XEGURIDAD_PASSWORD=${{ secrets.XEGURIDAD_PASSWORD }}" >> .env
        echo "PASSWORD_MONGO=${{ secrets.PASSWORD_MONGO }}" >> .env
        echo "NAMESPACE=Xeguridad" >> .env
        echo "repo_path=/home/exasa/XeguridadBot-produccion/XeguridadBot" >> .env
        echo "service=flask_main.service" >> .env
      if: github.ref == 'refs/heads/main'

    - name: Verify .env content
      run: cat .env

    - name: Push changes to GitHub
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/DanielFuentes918/XeguridadBot.git
        git push origin ${{ github.ref_name }}
